// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/supabase';
import { logger } from '@/lib/logger';

// #region agent log
fetch('http://127.0.0.1:7243/ingest/1c18bccf-ed41-47c5-9276-d3dce12ba107', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    sessionId: 'debug-session',
    runId: 'initial',
    hypothesisId: 'H1',
    location: 'src/integrations/supabase/client.ts:12',
    message: 'Reading Supabase env vars',
    data: {
      hasImportMetaEnv: typeof import.meta !== 'undefined' && !!import.meta.env,
      urlPresent: !!import.meta.env?.VITE_SUPABASE_URL,
      anonKeyPresent: !!import.meta.env?.VITE_SUPABASE_ANON_KEY,
    },
    timestamp: Date.now(),
  }),
}).catch(() => {});
// #endregion

// Temporarily hardcoded values - replace these with your actual Supabase URL and anon key
// In production, these should come from environment variables
export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
export const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// #region agent log
fetch('http://127.0.0.1:7243/ingest/1c18bccf-ed41-47c5-9276-d3dce12ba107', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    sessionId: 'debug-session',
    runId: 'initial',
    hypothesisId: 'H2',
    location: 'src/integrations/supabase/client.ts:24',
    message: 'Supabase env values after read',
    data: {
      supabaseUrlType: typeof supabaseUrl,
      supabaseAnonKeyType: typeof supabaseAnonKey,
      supabaseUrlEmpty: !supabaseUrl,
      supabaseAnonKeyEmpty: !supabaseAnonKey,
    },
    timestamp: Date.now(),
  }),
}).catch(() => {});
// #endregion

// Check if environment variables are set
if (!supabaseUrl || !supabaseAnonKey) {
  // #region agent log
  fetch('http://127.0.0.1:7243/ingest/1c18bccf-ed41-47c5-9276-d3dce12ba107', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      sessionId: 'debug-session',
      runId: 'initial',
      hypothesisId: 'H3',
      location: 'src/integrations/supabase/client.ts:37',
      message: 'Env vars missing branch taken',
      data: {
        supabaseUrl,
        supabaseAnonKeySet: !!supabaseAnonKey,
      },
      timestamp: Date.now(),
    }),
  }).catch(() => {});
  // #endregion

  logger.error('Supabase URL and Anon Key are required. Please set the VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY environment variables.');
  
  // Display a more helpful error in the console
  logger.log('\n-----------------------------------');
  logger.log('Environment Variables Missing');
  logger.log('-----------------------------------');
  logger.log('This application requires Supabase credentials to run.');
  logger.log('Please check ENV-SETUP.md for instructions on setting up your environment variables.');
  logger.log('-----------------------------------\n');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  supabaseUrl, 
  supabaseAnonKey
);